In [68]:
import torch


# Some Basic torch

In [69]:
# create an 1th-order tensor
x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [70]:
# inspect the len of a tensor

print(len(x))
print(x.numel())

12
12


In [71]:
# view the shape 
x.shape

torch.Size([12])

In [72]:
# reshape the tensor 
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [73]:
# reshape the tensor with automatic calculate 
X_auto_col = x.reshape(4,-1)
X_auto_row = x.reshape(-1,4)

print(X_auto_col)
print(X_auto_row)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [74]:
# create zero  tensor 
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [75]:
# create ones tensor 
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [76]:
# create tensor with random sample from gaussian distribution
torch.randn((2,3,4))

tensor([[[ 2.1710, -1.0038, -0.8670, -0.6026],
         [-0.6375,  0.2643,  0.8654, -0.6143],
         [-1.6699,  1.2390,  0.4841, -0.2150]],

        [[-0.5634,  0.0483, -0.7732, -0.0566],
         [ 0.1829,  1.0225, -0.3304, -2.4099],
         [-0.2509, -0.8913, -1.5403, -0.0837]]])

In [77]:
# custom a tensor the outermost list is axis = 0, the inner list corresponds is axis = 1
torch.tensor([[1,2,3,4], [5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

# Indexing and Slicing

In [78]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [79]:
# specific indices
X[1,2]
print(X)

# change that indicex value
X[1,2] = 20
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 20.,  7.],
        [ 8.,  9., 10., 11.]])


In [80]:
# assign multi element with the same value using slicing 
X[:2, :] = 0
X

tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 8.,  9., 10., 11.]])

# Operations

## Elementwise Operations 

In [81]:
# elementwise exp 

# unary - 1 input -> 1 output 
print(torch.exp(x))
print(x ** 2)
print(torch.sin(x))
print(torch.abs(x))


# binary - 2 input -> 1 output
# make that x and y has have the same shape
y = 2 * x
print(x * y)
print(x*2) # this still binary but it automatic compute elementwise =)) 
print(x+10)


tensor([1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])
tensor([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  64.,  81., 100., 121.])
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.9894,  0.4121, -0.5440, -1.0000])
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  9., 10., 11.])
tensor([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 128., 162., 200., 242.])
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 16., 18., 20., 22.])
tensor([10., 10., 10., 10., 10., 10., 10., 10., 18., 19., 20., 21.])


In [ ]:
# concatenate 
# ex perform concate with axis = 0

X = torch.arange(10).reshape(2,-1)
Y = torch.arange(10,20).reshape(2,-1)
print(X)
print(Y)


# perform concat 
Z = torch.cat((X, Y), dim=1)
print(Z)

# condition to cat 
# cat dim = 0, dim = 1 must equal, and vice versa 



tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])


In [85]:
# using logical statements 
Z = X == Y

print(Z)

tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [87]:
# some useful function 
X.sum()

tensor(45)

# broadcasting 

1. Quy tắc hoạt động (The Rules)

Để hai Tensor A và B có thể "Broadcast" được với nhau, chúng phải tuân thủ quy tắc nghiêm ngặt:

Quy tắc: So sánh kích thước (shape) của chúng từ Phải sang Trái (Right-to-Left). Tại mỗi chiều, hai kích thước phải thỏa mãn 1 trong 2 điều kiện:

    Chúng bằng nhau.

    Một trong hai kích thước bằng 1.

Nếu kích thước bị thiếu (ví dụ A là 3D, B là 1D), ta coi như kích thước bị thiếu là 1.

In [90]:
# the broadcasting auto stretching the another tensor to match shape 
A = torch.arange(6).reshape(3,-1)
print(A)
b = torch.arange(2).reshape(1,-1)
print(b)

res = A + b 
print(res)


tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 1]])
tensor([[0, 2],
        [2, 4],
        [4, 6]])


# Saving Memory

In [ ]:
# three way to save memory 
# using slicing [:]

Z[:] = X + Y

# using assignment operators 
Y += X 
# it equivalent with this 
Y.add_(X) # the _ mean in_place 

Y -= X
Y.sub_(X)

# work with other object 

In [92]:
a = torch.tensor([3.5])
# convert this to normal python or numpy object 

a.item(), float(a), int(a), a.numpy()

(3.5, 3.5, 3, array([3.5], dtype=float32))