In [1]:
import torch 




Quy ước chuẩn trong sách D2L (và Toán học cao cấp):

    Order (Bậc): Dùng để chỉ số lượng trục (số lượng chỉ số index cần dùng để truy cập phần tử).

        Vector có Order = 1 (1 trục).

        Matrix có Order = 2 (2 trục: hàng, cột).

        Tensor 3D có Order = 3.

    Dimensionality (Số chiều/Độ dài): Dùng để chỉ số lượng phần tử (components) bên trong vector đó.

In [2]:
# tranpose 
A = torch.randn(3,3)
print(A)

A == A.T
print(A * A**-1 )
print(A**-1 * A)

tensor([[ 0.2606,  1.0923, -0.5387],
        [ 1.1482, -0.5796,  0.5240],
        [ 0.0737,  0.0765, -0.9093]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


# testing with reducing

In [3]:
A = torch.arange(12, dtype= float).reshape(3,-1)
print(A) 
print(A.shape)
print(A.sum(axis=0))
print(A.sum(axis=0).shape)


# testing with reducing axis = 1 

A = torch.arange(3*4*5*6*7, dtype=float).reshape(3,4,5,6,-1)
print(A)
print(A.shape)
print(A.sum(axis=0))
print(A.sum(axis=0).shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)
torch.Size([3, 4])
tensor([12., 15., 18., 21.], dtype=torch.float64)
torch.Size([4])
tensor([[[[[0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 4.0000e+00,
            5.0000e+00, 6.0000e+00],
           [7.0000e+00, 8.0000e+00, 9.0000e+00,  ..., 1.1000e+01,
            1.2000e+01, 1.3000e+01],
           [1.4000e+01, 1.5000e+01, 1.6000e+01,  ..., 1.8000e+01,
            1.9000e+01, 2.0000e+01],
           [2.1000e+01, 2.2000e+01, 2.3000e+01,  ..., 2.5000e+01,
            2.6000e+01, 2.7000e+01],
           [2.8000e+01, 2.9000e+01, 3.0000e+01,  ..., 3.2000e+01,
            3.3000e+01, 3.4000e+01],
           [3.5000e+01, 3.6000e+01, 3.7000e+01,  ..., 3.9000e+01,
            4.0000e+01, 4.1000e+01]],

          [[4.2000e+01, 4.3000e+01, 4.4000e+01,  ..., 4.6000e+01,
            4.7000e+01, 4.8000e+01],
           [4.9000e+01, 5.0000e+01, 5.1000e+01,  ..., 5.3000e+01,
            5.

In [4]:
# get the average 
A.mean(), A.sum() / A.numel()

(tensor(1259.5000, dtype=torch.float64),
 tensor(1259.5000, dtype=torch.float64))

In [5]:
# test between numel and len 
print(len(A)) # this only count for first axis = 0
print(A.numel())


3
2520


In [6]:
# non-reduction sum 
A = torch.arange(9, dtype=float).reshape(3,-1)
sum_A = A.sum(axis=0, keepdim=True)
print(sum_A)
print(sum_A.shape)


# this use for broadcasting
# ex: 
A / sum_A

tensor([[ 9., 12., 15.]], dtype=torch.float64)
torch.Size([1, 3])


tensor([[0.0000, 0.0833, 0.1333],
        [0.3333, 0.3333, 0.3333],
        [0.6667, 0.5833, 0.5333]], dtype=torch.float64)

# CUMSUM

In [7]:
print(A)
print(A.cumsum(axis=0))
print(A.cumsum(axis=1))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)
tensor([[ 0.,  1.,  2.],
        [ 3.,  5.,  7.],
        [ 9., 12., 15.]], dtype=torch.float64)
tensor([[ 0.,  1.,  3.],
        [ 3.,  7., 12.],
        [ 6., 13., 21.]], dtype=torch.float64)


# dot product / inner product

In [8]:
x = torch.arange(3)
y = torch.arange(3,6)

print(torch.dot(x, y))
print(torch.dot(y,x))
print(torch.sum(x * y))

tensor(14)
tensor(14)
tensor(14)


In [9]:
# matrix mul 
A.shape, x.shape, torch.mv(A, x), A @ x

RuntimeError: expected scalar type Double but found Long

In [ ]:
B = torch.ones(3,4, dtype=float)

torch.mm(A, B), A @ B

# NORM 

‖αx‖ = |α| · ‖x‖


‖x + y‖ ≤ ‖x‖ + ‖y‖


A norm is a function

that maps a vector to a scalar and satisfies the following three properties:

    Given any vector 

, if we scale (all elements of) the vector by a scalar

, its norm scales accordingly:
(2.3.10)

For any vectors
and

: norms satisfy the triangle inequality:
(2.3.11)

The norm of a vector is nonnegative and it only vanishes if the vector is zero:
(2.3.12)


In [ ]:
# norm, default of pytorch is l2 norm 
u = torch.tensor([3.0, -4.0])

l2_norm_u = torch.norm(u)

print(l2_norm_u)

In [ ]:
# custom l1 norm 

l1_norm_u = torch.abs(torch.sum(u))

print(l1_norm_u)

In [ ]:
# if we use norm, it mean apply frobenius norm 
torch.norm(torch.ones(3,4))

